# Project information
site_name: "Roger Cormier – Digital Strategy & Execution"
site_description: "Personal portfolio website using MkDocs Material."
site_author: "rogerleecormier"
site_url: "https://rogerleecormier.github.io/"

# Navigation
#nav:
#  - Home: index.md
#  - Data Analytics: data-analytics/index.md
#  - Cloud & DevOps Engineering: cloud-devops/index.md
#  - ERP & SaaS Integration: erp-saas/index.md
#  - Digital Transformation Strategy: strategy/index.md
#  - Technical Project Leadership: leadership/index.md
#  - Contact: contact.md

# Copyright
copyright: "&copy; 2025 Roger Lee Cormier. All rights reserved."

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/rogerleecormier"
edit_uri: "https://github.com/rogerleecormier/edit/main/docs"

# Configuration
docs_dir: "docs"
theme:
  name: material
  logo: assets/images/logo-white.svg
  palette:
    - scheme: default
      primary: teal       # change from indigo → teal
      accent: deeporange  # change from indigo → deeporange
      primary_hue: 700     # picks #00897B
      accent_hue: 300      # picks #FF7043
      background: "#FAFAFA"
      text:       "#212121"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: teal         # change from orange → teal
      accent: deeporange    # change from orange → deeporange
      primary_hue: 200       # picks #4DB6AC
      accent_hue: 200        # picks #FF8A65
      background: "#121212"
      text:       "#E0E0E0"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: 'assets/images/favicon.ico'
#use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"
      toc_depth: 2-3   # Only show h2 and h3 in the ToC/anchors

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - awesome-nav:
  - social:
      cards_layout_options:
        title: "Roger Cormier"
        description: "Digital Strategy & Execution"

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
  - "https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"
  - "js/ga4.js"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/linkedin"
      link: "https://linkedin.com/in/rogerleecormier"
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/rogerleecormier"
    - icon: "fontawesome/brands/facebook"
      link: "https://facebook.com/rogerleejcormier"