# Project information
site_name: "Roger Cormier – Digital Strategy & Execution"
site_description: "Personal portfolio website using MkDocs Material."
site_author: "rogerleecormier"
site_url: "https://rogerleecormier.github.io/"

# Navigation
#nav:
#  - Home: index.md
#  - Data Analytics: data-analytics/index.md
#  - Cloud & DevOps Engineering: cloud-devops/index.md
#  - ERP & SaaS Integration: erp-saas/index.md
#  - Digital Transformation Strategy: strategy/index.md
#  - Technical Project Leadership: leadership/index.md
#  - Contact: contact.md

# Copyright
copyright: "&copy; 2021 rogerleecormier"

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/rogerleecormier"
edit_uri: "https://github.com/rogerleecormier/edit/main/docs"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  logo: images/logo-white.svg
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  #favicon: 'assets/images/favicon.ico'
#use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"
      toc_depth: 2-3   # Only show h2 and h3 in the ToC/anchors

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - awesome-nav

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/rogerleecormier"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/rogerleecormier"